<template>
  <iframe
    src="https://ghbtns.com/github-btn.html?user=bocadilloproject&repo=bocadillo&type=star&count=true&size=large"
    frameborder="0"
    scrolling="0"
    width="130px"
    height="30px"
  ></iframe>
</template>
